version: '3'

services:
  traefik-http-shaping:
    restart: always
    network_mode: "host"
    # The official v2 Traefik docker image
    image: traefik:v2.6
    # Enables the web UI and tells Traefik to listen to docker
    #ports:
    #  - "80:80"
    #  - "443:443"
    #  - "8080:8080"

    logging:
      driver: "json-file"
      options:
        max-size: "100m"

    volumes:
      - ./traefik-dev.yml:/etc/traefik/traefik.yml
      - ./.traefik.yml:/plugins-local/src/github.com/martinlevesque/http_shaping/.traefik.yml
      - ./go.mod:/plugins-local/src/github.com/martinlevesque/http_shaping/go.mod
      - ./http_shaping.go:/plugins-local/src/github.com/martinlevesque/http_shaping/http_shaping.go
      - ./configs-dev/:/configs/